ModmailTicketer/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'', include("social.apps.django_app.urls", namespace="social")),
	url(r'', include("main.urls", namespace="main")),
]

handler404 = "main.views.handler404"

if settings.DEBUG:
	urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.contrib import admin
from django.conf.urls import url
from . import views

urlpatterns = [
	url("^$", views.index, name="index"),
	url("^help/$", views.help, name="help"),
	url("^logout/$", views.logout, name="logout"),
	
	url("^r/(?P<subreddit>[a-zA-Z0-9_]+)/$", views.subreddit_all, name="subreddit"),
	url("^r/(?P<subreddit>[a-zA-Z0-9_]+)/all/$", views.subreddit_all, name="subreddit_all"),
	url("^r/(?P<subreddit>[a-zA-Z0-9_]+)/open/$", views.subreddit_open, name="subreddit_open"),
	url("^r/(?P<subreddit>[a-zA-Z0-9_]+)/active/$", views.subreddit_active, name="subreddit_active"),
	url("^r/(?P<subreddit>[a-zA-Z0-9_]+)/closed/$", views.subreddit_closed, name="subreddit_closed"),
	url("^r/(?P<subreddit>[a-zA-Z0-9_]+)/ignored/$", views.subreddit_ignored, name="subreddit_ignored"),
	url("^r/(?P<subreddit>[a-zA-Z0-9_]+)/mine/$", views.subreddit_mine, name="subreddit_mine"),
	url("^r/(?P<subreddit>[a-zA-Z0-9_]+)/settings/$", views.subreddit_config, name="subreddit_config"),
	
	url("^api/ticket/(?P<ticket_id>[a-zA-Z0-9]+)/$", views.get_message_body, name="get_message_body"),
	url("^api/ticket/(?P<ticket_id>[a-zA-Z0-9]+)/modify/$", views.modify_ticket, name="modify_ticket"),
]

admin.site.site_title = "Modmail Ticketer"
admin.site.site_header = "Modmail Ticketer Administration"
#admin.site.index_title = "Site administration"

main/models.py
from django.db import models
from django.contrib.auth.models import User

import enum
from django.db.models import Q


class Redditor(models.Model):
	id = models.CharField(max_length=5, primary_key=True)
	user = models.OneToOneField(User, blank=True, null=True)
	name = models.CharField(max_length=20)
	
	def get_subreddits(self):
		return self.moderates_set.all().order_by("name")
	
	def __str__(self):
		return "/u/{}".format(self.name)

class Subreddit(models.Model):
	id = models.CharField(max_length=5, primary_key=True)
	name = models.CharField(max_length=20)
	moderators = models.ManyToManyField(Redditor, related_name="moderates_set")
	
	enabled = models.BooleanField(default=True)
	bots = models.CharField(max_length=209, default="AutoModerator", blank=True)
	hl_users = models.CharField(max_length=209, default="", blank=True)
	
	auto_respond = models.BooleanField(default=False)
	auto_respond_new = models.BooleanField(default=True)
	auto_respond_new_text = models.TextField(max_length=800, blank=True, default="")
	auto_respond_closed = models.BooleanField(default=False)
	auto_respond_closed_text = models.TextField(max_length=800, blank=True, default="")
	
	def get_status_tickets(self, status):
		if status is None:
			return self.ticket_set.none()
		return self.ticket_set.filter(status=status)
	
	def get_user_tickets(self, redditor):
		if redditor is None:
			return self.ticket_set.none()
		status_q = Q(status=Ticket.Status.ACTIVE)
		status_q |= Q(status=Ticket.Status.OPEN)
		q = Q(status_q)
		q &= Q(modified_by=redditor)
		return self.ticket_set.filter(q)
	
	def get_num_open_tickets(self):
		return self.ticket_set.filter(status=Ticket.Status.OPEN).count()
	
	def get_num_user_tickets(self, redditor):
		return self.get_user_tickets(redditor).count()
	
	def user_moderates(self, user):
		if user is None or not user.is_authenticated():
			return False
		return self.moderators.filter(user=user).count() > 0
	
	def __str__(self):
		return "/r/{}".format(self.name)

class Message(models.Model):
	id = models.CharField(max_length=6, primary_key=True)
	subject = models.CharField(max_length=100, blank=True)
	sender = models.CharField(max_length=20, blank=True)
	sender_id = models.CharField(max_length=5, blank=True)
	
	def get_num_replies(self):
		return self.replies.count()
	
	def __str__(self):
		return "Message {}".format(self.pk)

class MessageReply(models.Model):
	id = models.CharField(max_length=6, primary_key=True)
	sender = models.CharField(max_length=20, blank=True)
	sender_id = models.CharField(max_length=5, blank=True)
	
	trunk_message = models.ForeignKey(Message, related_name="replies")
	parent_reply = models.ForeignKey("self", related_name="replies", blank=True, null=True)

class Ticket(models.Model):
	message = models.OneToOneField(Message)
	subreddit = models.ForeignKey(Subreddit)
	
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	date_edited = models.DateTimeField(auto_now=True, null=True)
	modified_by = models.ForeignKey(Redditor, null=True, blank=True)
	
	is_flagged = models.BooleanField(default=False)
	
	class Type(enum.IntEnum):
		NORMAL = 0
		BAN = 1
		BOT = 2
		MOD = 3
		ADMIN = 4
	type = models.PositiveSmallIntegerField(default=Type.NORMAL.value)
	
	class Status(enum.IntEnum):
		OPEN = 0
		ACTIVE = 1
		CLOSED = 2
		IGNORED = 3
	status = models.PositiveSmallIntegerField(default=Status.OPEN.value)
	
	def __str__(self):
		return "Ticket {}".format(self.pk)

main/forms.py
from django.forms import forms, fields, ModelForm
from main.models import Subreddit

class SubredditForm(ModelForm):
	class Meta:
		model = Subreddit
		fields = ["bots", "hl_users",
				  "auto_respond",
				  "auto_respond_new", "auto_respond_new_text",
				  "auto_respond_closed", "auto_respond_closed_text"]

main/templatetags/forms.py
from django_jinja import library
from widget_tweaks.templatetags import widget_tweaks

@library.filter()
def add_class(field, css_class):
	return widget_tweaks.add_class(field, css_class)

main/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseForbidden, HttpResponseBadRequest, Http404
from django.views.decorators.http import require_safe, require_POST, require_GET
from django.contrib import auth
from django.shortcuts import render, redirect, get_object_or_404
from main.forms import SubredditForm
from main.templatetags.stringify import get_status_class, get_status_label_class, get_status_string

from .models import Subreddit, Redditor, Ticket
from .func import reddit_util

@require_safe
def index(request):
	return render_main_page(request)

@require_safe
def help(request):
	raise Http404()

@require_safe
def subreddit_all(request, subreddit):
	return render_main_page(request, subreddit)

@require_safe
def subreddit_open(request, subreddit):
	return render_main_page(request, subreddit, status_filter=Ticket.Status.OPEN)

@require_safe
def subreddit_active(request, subreddit):
	return render_main_page(request, subreddit, status_filter=Ticket.Status.ACTIVE)

@require_safe
def subreddit_closed(request, subreddit):
	return render_main_page(request, subreddit, status_filter=Ticket.Status.CLOSED)

@require_safe
def subreddit_ignored(request, subreddit):
	return render_main_page(request, subreddit, status_filter=Ticket.Status.IGNORED)

@require_safe
def subreddit_mine(request, subreddit):
	return render_main_page(request, subreddit, custom_filter="mine")

def render_main_page(request, subreddit=None, status_filter=None, custom_filter=None, order=None, limit=100):
	if subreddit is None:
		return render(request, "main/index.jinja")
	
	# Subreddit info
	subreddit = get_subreddit(subreddit)
	if subreddit is None:
		return render_subreddit_404(request, subreddit)
	if not subreddit.user_moderates(request.user) or not subreddit.enabled:
		return render_subreddit_401(request, subreddit)
	
	# Get ticket list
	print("Status: {}".format(status_filter))
	if status_filter is not None:
		tickets = subreddit.get_status_tickets(status_filter)
	elif custom_filter is not None:
		if custom_filter == "mine":
			tickets = subreddit.get_user_tickets(request.user.redditor)
		else:
			print("Warning: Invalid custom ticket filter")
			tickets = subreddit.ticket_set.all()
	else:
		tickets = subreddit.ticket_set.all()
	
	# Apply modifiers to ticket list
	tickets = tickets.order_by("-id" if order is None else order)
	tickets = tickets[:limit]
	
	return render(request, "main/subreddit.jinja", {"subreddit": subreddit, "tickets": tickets, "status_filter": status_filter, "custom_filter": custom_filter})

@login_required
def subreddit_config(request, subreddit):
	# Subreddit info
	subreddit = get_subreddit(subreddit)
	if subreddit is None:
		return render_subreddit_404(request, subreddit)
	if not subreddit.user_moderates(request.user) or not subreddit.enabled:
		return render_subreddit_401(request, subreddit)
	
	if request.method == "POST":
		form = SubredditForm(request.POST, instance=subreddit)
		if form.is_valid():
			form.save()
			return redirect("main:subreddit", subreddit.name)
	else:
		form = SubredditForm(instance=subreddit)
		return render(request, "main/subreddit_config.jinja", {"subreddit": subreddit, "form": form, "custom_filter": "settings"})

# Authentication

def logout(request):
	#request.session["token"] = None
	#request.session.flush()
	auth.logout(request)
	return redirect("/")

# Other

def handler404(request):
	resp = render(request, "main/404.jinja")
	resp.status_code = 404
	return resp

# API methods

@login_required
@require_POST
def modify_ticket(request, ticket_id):
	print("Modifying ticket {}".format(ticket_id))
	ticket = get_object_or_404(Ticket, id=ticket_id)
	if not ticket.subreddit.user_moderates(request.user):
		return HttpResponseForbidden()
	
	def finalize_success():
		ticket.modified_by = request.user.redditor
		ticket.save()
	
	# Find and perform the operation
	if "inc_status" in request.GET:
		inc_status = request.GET["inc_status"]
		status = Ticket.Status[inc_status.upper()]
		# Increment the status
		if status < Ticket.Status.CLOSED:
			status += 1
		else:
			return JsonResponse({"success": False})
		
		# Update status
		ticket.status = status
		finalize_success()
		
		return JsonResponse({
			"success": True,
			"status": get_status_class(status),
			"status_class": get_status_label_class(status),
			"status_text": get_status_string(status)
		})
	if "set_status" in request.GET:
		set_status = request.GET["set_status"]
		status = Ticket.Status[set_status.upper()]
		
		# Update status
		ticket.status = status
		finalize_success()
		
		return JsonResponse({
			"success": True,
			"status": get_status_class(status),
			"status_class": get_status_label_class(status),
			"status_text": get_status_string(status)
		})
	if "set_flagged" in request.GET:
		set_flagged = request.GET["set_flagged"] == "1"
		if (set_flagged and not ticket.is_flagged) or (not set_flagged and ticket.is_flagged):
			ticket.is_flagged = set_flagged
			ticket.save()
			print(ticket.is_flagged)
		
		return JsonResponse({
			"success": True,
			"flagged":  set_flagged
		})
	
	return HttpResponseBadRequest()

@login_required
@require_GET
def get_message_body(request, ticket_id):
	print("Getting message text {}".format(ticket_id))
	ticket = get_object_or_404(Ticket, id=ticket_id)
	if not ticket.subreddit.user_moderates(request.user):
		return HttpResponseForbidden()
	
	if ticket.type == Ticket.Type.BAN:
		message = reddit_util.get_message_body_html(request.user, ticket.message.id, offset=1)
	else:
		message = reddit_util.get_message_body_html(request.user, ticket.message.id)
	
	if message:
		return JsonResponse({
				"success": True,
				"message": message,
			})
	
	return JsonResponse({
			"success": False
		})

# Util

def get_subreddit(subreddit):
	try:
		return Subreddit.objects.get(name=subreddit)
	except Subreddit.DoesNotExist:
		return None
	except Subreddit.MultipleObjectsReturned:
		print("This should never happen!")
		return None

def render_subreddit_404(request, subreddit):
	return render(request, "main/subreddit_error.jinja", {"subreddit": subreddit, "error": "that subreddit does not exist"})

def render_subreddit_401(request, subreddit):
	return render(request, "main/subreddit_error.jinja", {"subreddit": subreddit, "error": "you are not authorized to view that subreddit"})

main/templates/main/comp/center/config.jinja
<div class="alert alert-warning" role="alert"><b>Warning:</b>This page is incomplete and is not yet intended for public use.</div>
<h1 class="page-header">/r/{{ subreddit.name }} settings</h1>
<form method="post">
	{% csrf_token %}
	
	<div class="panel panel-default">
		<div class="panel-heading">
			<h2 class="panel-title">ticket settings</h2>
		</div>
		<div class="panel-body">
			<div class="form-group">
				<label for="id_bots">bots</label>
				{{ form.bots|add_class("form-control") }}
				<span class="help-block">bot names separated by a comma, case-insensitive</span>
			</div>
			<div class="form-group">
				<label for="id_hl_users">highlight users</label>
				{{ form.hl_users|add_class("form-control") }}
				<span class="help-block">user names separated by a comma, case-insensitive</span>
			</div>
		</div>
	</div>
	
	<div class="panel panel-default">
		<div class="panel-heading">
			<h2 class="panel-title">auto-responder settings</h2>
		</div>
		<div class="panel-body">
			<span class="help-block">Automatic responses can be configured to leave replies on mod mails at different stages.</span>
			<div class="checkbox">
				<label>{{ form.auto_respond|add_class("form-switch") }} <b>enable automatic responses</b></label>
			</div>
			<div class="form-group">
				<div class="checkbox">
					<label>{{ form.auto_respond_new|add_class("form-switch") }} enable new message response</label>
				</div>
				{{ form.auto_respond_new_text|add_class("form-control") }}
			</div>
			<div class="form-group">
				<div class="checkbox">
					<label>{{ form.auto_respond_closed|add_class("form-switch") }} enable response when ticket is closed</label>
				</div>
				{{ form.auto_respond_closed_text|add_class("form-control") }}
			</div>
		</div>
	</div>
	
	<button type="submit" class="btn btn-primary">save</button>
</form>

main/templates/main/comp/center/error.jinja
<div id="no-messages">
	<p class="info-message error-message">{{ error }}</p>
</div>

main/templates/main/comp/center/null.jinja
<div id="no-messages">
{% if request.user.is_authenticated() %}
	<p class="info-message">select a subreddit to view tickets</p>
{% else %}
	<p class="info-message">log in to view your subreddits</p>
{% endif %}
</div>

main/templates/main/comp/center/subreddit.jinja
<table id="message-list" class="table table-striped table-hover">
	<thead>
		<tr>
			<th class="col-date">created</th>
			<th class="col-type">type</th>
			<th class="col-subject">subject</th>
			<th class="col-sender">sender</th>
			<th class="col-replies">replies</th>
			<th class="col-status">status</th>
		</tr>
	</thead>
	<tbody>
	{% for ticket in tickets %}
		{% include "main/comp/center/subreddit_ticket.jinja" %}
	{% endfor %}
	</tbody>
</table>

{% if tickets|length() == 0 and get_status_class(status_filter) == "open" %}
<div id="no-messages">
	<p class="info-message">you have no open tickets</p>
	<p class="info-message">good job!</p>
</div>
{% endif %}

main/templates/main/comp/center/subreddit_ticket.jinja
{# Ticket info #}
{% set message = ticket.message %}
{% if ticket.modified_by %}
	{% set last_modified = ticket.modified_by.name %}
	{% if request.user.redditor.name == last_modified %}
		{% set last_modified = last_modified + " (that's you!)" %}
	{% endif %}
{% else %}
	{% set last_modified = "a ghost" %}
{% endif %}

{# Ticket render #}
<tr class="ticket{% if ticket.is_flagged %} flagged{% endif %}" data-ticket-id="{{ ticket.id }}" data-ticket-status="{{ get_status_class(ticket.status) }}" data-last-modified-by="{{ last_modified }}">
	<td class="col-date"><span class="date" title="{{ ticket.date_created }}">{{ humanize_date(ticket.date_created) }}</span></td>
	<td class="col-type">
		<span class="label label-{{ get_type_label_class(ticket.type) }}">{{ get_type_string(ticket.type) }}</span>
	</td>
	<td class="col-subject"><a class="subject" href="{{ get_message_url(message.id) }}" target="_blank">{{ message.subject }}</a></td>
	<td class="col-sender"><a href="{{ get_redditor_url(message.sender) }}" target="_blank">{{ message.sender }}</a></td>
	<td class="col-replies">{{ message.get_num_replies() }}</td>
	<td class="col-status">
		<div class="btn-group">
			{% set status_class = get_status_label_class(ticket.status) %}
			
			<a href="javascript:" class="status-button btn btn-xs btn-{{ status_class }}">{{ get_status_string(ticket.status) }}</a>
			<button type="button" class="status-dropdown-button btn btn-xs btn-{{ status_class }} dropdown-toggle" data-toggle="dropdown">
				<span class="caret"></span>
			</button>
			<ul class="dropdown-menu">
				<li><a class="status-button-set text-success" status="open" href="javascript:">Open</a></li>
				<li><a class="status-button-set text-primary" status="active" href="javascript:">Active</a></li>
				<li><a class="status-button-set text-muted" status="closed" href="javascript:">Closed</a></li>
				<li><a class="status-button-set text-danger" status="ignored" href="javascript:">Ignored</a></li>
			</ul>
		</div>
		<a href="javascript:" class="flag-button btn btn-xs btn-default"><span class="glyphicon glyphicon-flag"></span></a>
	</td>
</tr>